# Generated by Django 3.1.5 on 2021-04-15 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='category_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products')),
                ('image1', models.FileField(upload_to='products')),
                ('image2', models.FileField(upload_to='products')),
                ('name', models.CharField(default='', max_length=100)),
                ('price1', models.CharField(default='', max_length=300)),
                ('price2', models.CharField(default='', max_length=300)),
                ('price3', models.CharField(default='', max_length=300)),
                ('price4', models.CharField(default='', max_length=300)),
                ('price5', models.CharField(default='', max_length=300)),
                ('cid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cake_app.category_tb')),
            ],
        ),
        migrations.CreateModel(
            name='order_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=100)),
                ('quantity', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=100)),
                ('pid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cake_app.product_tb')),
            ],
        ),
    ]
