# Generated by Django 3.1.5 on 2021-04-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='', max_length=100)),
                ('last', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('pin', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('oid', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cake_app.order_tb')),
            ],
        ),
    ]
