# Generated by Django 3.1.5 on 2023-12-10 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0003_touch_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
