# Generated by Django 3.1.5 on 2023-12-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0004_product_tb_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
