# Generated by Django 3.1.5 on 2023-12-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0007_product_tb_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tb',
            name='createdat',
        ),
    ]
