# Generated by Django 3.1.5 on 2023-12-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0008_remove_product_tb_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tb',
            name='created_at',
        ),
    ]
